export interface PresetTrack {
  youtubeId: string;
  title: string;
  artist: string;
  album: string;
  cover: string | null;
}

export interface PresetPlaylist {
  id: string;
  name: string;
  hindiName: string;
  slot: string;
  description: string;
  sourceUrl: string;
  tracks: PresetTrack[];
}

export const PRESET_PLAYLISTS: PresetPlaylist[] = [
  {
    id: "highway-raat",
    name: "Highway Raat",
    hindiName: "हाईवे रात",
    slot: "22:00–05:00 IST",
    description: "The truck-cabin canon — the long dark national-highway stretch. Heavy on separation, distance and letters from home.",
    sourceUrl: "https://www.deluxesaloon.space/playlists/highway-raat",
    tracks: [
      { youtubeId: "yexZf8g_dJw", title: "Chitthi Aayi Hai", artist: "Pankaj Udhas", album: "Naam", cover: "https://i.ytimg.com/vi/yexZf8g_dJw/hqdefault.jpg" },
      { youtubeId: "YczkDMTaek4", title: "Sandese Aate Hain", artist: "Sonu Nigam, Roop Kumar Rathod", album: "Border", cover: "https://i.ytimg.com/vi/YczkDMTaek4/hqdefault.jpg" },
      { youtubeId: "70YFS4GvuQ0", title: "Chhod Aaye Hum Woh Galiyan", artist: "Hariharan, Suresh Wadkar, K. S. Chithra, Vinod Sehgal", album: "Maachis", cover: "https://i.ytimg.com/vi/70YFS4GvuQ0/hqdefault.jpg" },
      { youtubeId: "PUGaSHPdTGg", title: "Sochenge Tumhe Pyar", artist: "Kumar Sanu", album: "Deewana", cover: "https://i.ytimg.com/vi/PUGaSHPdTGg/hqdefault.jpg" },
      { youtubeId: "_IcVb6hFhPs", title: "Ghar Se Nikalte Hi", artist: "Udit Narayan", album: "Papa Kehte Hain", cover: "https://i.ytimg.com/vi/_IcVb6hFhPs/hqdefault.jpg" },
      { youtubeId: "EhOQvAe6bfM", title: "Jab Koi Baat Bigad Jaye", artist: "Kumar Sanu, Sadhana Sargam", album: "Jurm", cover: "https://i.ytimg.com/vi/EhOQvAe6bfM/hqdefault.jpg" },
      { youtubeId: "Kidtrrn4aUM", title: "Kuch Na Kaho", artist: "Kumar Sanu", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/Kidtrrn4aUM/hqdefault.jpg" },
      { youtubeId: "FD3vgLOEdgk", title: "Jaadu Teri Nazar", artist: "Udit Narayan", album: "Darr", cover: "https://i.ytimg.com/vi/FD3vgLOEdgk/hqdefault.jpg" },
      { youtubeId: "rTatsmUgmiA", title: "Ab Tere Bin Jee Lenge Hum", artist: "Kumar Sanu", album: "Aashiqui", cover: "https://i.ytimg.com/vi/rTatsmUgmiA/hqdefault.jpg" },
      { youtubeId: "l7iTcZ__Ejg", title: "Jaati Hoon Main", artist: "Kumar Sanu, Alka Yagnik", album: "Karan Arjun", cover: "https://i.ytimg.com/vi/l7iTcZ__Ejg/hqdefault.jpg" },
      { youtubeId: "jBpRItrod-Q", title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/jBpRItrod-Q/hqdefault.jpg" },
      { youtubeId: "lZLxjLYyhYQ", title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh, Sapna Awasthi", album: "Dil Se..", cover: "https://i.ytimg.com/vi/lZLxjLYyhYQ/hqdefault.jpg" },
      { youtubeId: "As9DnNT3XZA", title: "Akele Hain To Kya Gham Hai", artist: "Udit Narayan, Alka Yagnik", album: "Qayamat Se Qayamat Tak", cover: "https://i.ytimg.com/vi/As9DnNT3XZA/hqdefault.jpg" },
      { youtubeId: "PhkADyPektU", title: "Aate Jaate Haste Gaate", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/PhkADyPektU/hqdefault.jpg" },
      { youtubeId: "BkLOBuTAtS0", title: "Mere Rang Mein Rangne Wali", artist: "S. P. Balasubrahmanyam", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/BkLOBuTAtS0/hqdefault.jpg" },
      { youtubeId: "fBylcT-TWZw", title: "Bas Ek Sanam Chahiye", artist: "Kumar Sanu", album: "Aashiqui", cover: "https://i.ytimg.com/vi/fBylcT-TWZw/hqdefault.jpg" },
      { youtubeId: "otQmzlm-s7Q", title: "Main Duniya Bhula Doonga", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/otQmzlm-s7Q/hqdefault.jpg" },
      { youtubeId: "YCuhzjK11iA", title: "Saanson Ki Zaroorat Hai Jaise", artist: "Kumar Sanu", album: "Aashiqui", cover: "https://i.ytimg.com/vi/YCuhzjK11iA/hqdefault.jpg" },
      { youtubeId: "ijGumwamEQU", title: "Jumma Chumma De De", artist: "Sudesh Bhosle, Kavita Krishnamurthy", album: "Hum", cover: "https://i.ytimg.com/vi/ijGumwamEQU/hqdefault.jpg" },
      { youtubeId: "_T-NphgkgVc", title: "Koi Na Koi Chahiye", artist: "Kumar Sanu", album: "Deewana", cover: "https://i.ytimg.com/vi/_T-NphgkgVc/hqdefault.jpg" },
      { youtubeId: "pYDbGCEUN40", title: "Yeh Haseen Vadiyan", artist: "S. P. Balasubrahmanyam, K. S. Chithra", album: "Roja", cover: "https://i.ytimg.com/vi/pYDbGCEUN40/hqdefault.jpg" },
      { youtubeId: "Cn3FAEQMnO4", title: "Baazigar O Baazigar", artist: "Kumar Sanu, Alka Yagnik", album: "Baazigar", cover: "https://i.ytimg.com/vi/Cn3FAEQMnO4/hqdefault.jpg" },
      { youtubeId: "fg9G1dacXjk", title: "Chhupana Bhi Nahi Aata", artist: "Vinod Rathod", album: "Baazigar", cover: "https://i.ytimg.com/vi/fg9G1dacXjk/hqdefault.jpg" },
      { youtubeId: "3OXiqmUhB70", title: "Choli Ke Peeche", artist: "Ila Arun, Alka Yagnik", album: "Khal Nayak", cover: "https://i.ytimg.com/vi/3OXiqmUhB70/hqdefault.jpg" },
      { youtubeId: "tfSqvusJiFI", title: "Likha Hai Teri Aankhon Mein", artist: "Kumar Sanu, Lata Mangeshkar", album: "Darr", cover: "https://i.ytimg.com/vi/tfSqvusJiFI/hqdefault.jpg" },
      { youtubeId: "7egtbySpvfw", title: "Ae Kaash Ke Hum", artist: "Kumar Sanu", album: "Kabhi Haan Kabhi Naa", cover: "https://i.ytimg.com/vi/7egtbySpvfw/hqdefault.jpg" },
      { youtubeId: "T7IZuj5fvYM", title: "Is Tarah Aashiqui Ka", artist: "Kumar Sanu", album: "Imtihan", cover: "https://i.ytimg.com/vi/T7IZuj5fvYM/hqdefault.jpg" },
      { youtubeId: "nopOmxeaCLA", title: "Lo Chali Main", artist: "Lata Mangeshkar", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/nopOmxeaCLA/hqdefault.jpg" },
      { youtubeId: "fPbDOCBx11w", title: "Na Kajre Ki Dhaar", artist: "Pankaj Udhas, Sadhana Sargam", album: "Mohra", cover: "https://i.ytimg.com/vi/fPbDOCBx11w/hqdefault.jpg" },
      { youtubeId: "Qq-qu2PNuKg", title: "Rim Jhim Rim Jhim", artist: "Kumar Sanu, Kavita Krishnamurthy", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/Qq-qu2PNuKg/hqdefault.jpg" },
      { youtubeId: "0UJbl8H3_No", title: "Yeh Mausam Ka Jadoo", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/0UJbl8H3_No/hqdefault.jpg" },
      { youtubeId: "3z7tf28mR90", title: "Aisa Zakhm Diya Hai", artist: "Kumar Sanu", album: "Akele Hum Akele Tum", cover: "https://i.ytimg.com/vi/3z7tf28mR90/hqdefault.jpg" },
      { youtubeId: "dHzSmJGSnIc", title: "Akhiyaan Milaoon Kabhi", artist: "Udit Narayan, Alka Yagnik", album: "Raja", cover: "https://i.ytimg.com/vi/dHzSmJGSnIc/hqdefault.jpg" },
      { youtubeId: "mSu5cz2GFts", title: "Dil Mera Churaya Kyun", artist: "Kumar Sanu", album: "Akele Hum Akele Tum", cover: "https://i.ytimg.com/vi/mSu5cz2GFts/hqdefault.jpg" },
      { youtubeId: "11v9ALkOiio", title: "Hai Rama", artist: "Hariharan, Swarnalatha", album: "Rangeela", cover: "https://i.ytimg.com/vi/11v9ALkOiio/hqdefault.jpg" },
      { youtubeId: "2tTxFyOS3Fo", title: "Humma Humma", artist: "Remo Fernandes, Swarnalatha", album: "Bombay", cover: "https://i.ytimg.com/vi/2tTxFyOS3Fo/hqdefault.jpg" },
      { youtubeId: "YdmHOtMM8Yc", title: "Nazrein Mili Dil Dhadka", artist: "Udit Narayan, Alka Yagnik", album: "Raja", cover: "https://i.ytimg.com/vi/YdmHOtMM8Yc/hqdefault.jpg" },
      { youtubeId: "W1GNGlaFKYw", title: "Tanha Tanha", artist: "Asha Bhosle", album: "Rangeela", cover: "https://i.ytimg.com/vi/W1GNGlaFKYw/hqdefault.jpg" },
      { youtubeId: "waTwDgK2tkk", title: "Tu Hi Re", artist: "Hariharan, Kavita Krishnamurthy", album: "Bombay", cover: "https://i.ytimg.com/vi/waTwDgK2tkk/hqdefault.jpg" },
      { youtubeId: "vIyNwuPTafk", title: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan", album: "Raja Hindustani", cover: "https://i.ytimg.com/vi/vIyNwuPTafk/hqdefault.jpg" },
      { youtubeId: "0vXTVXM6HEE", title: "Ho Nahi Sakta", artist: "Kumar Sanu", album: "Diljale", cover: "https://i.ytimg.com/vi/0vXTVXM6HEE/hqdefault.jpg" },
      { youtubeId: "wV8njoRVefQ", title: "Kitna Pyara Tujhe Rab Ne Banaya", artist: "Udit Narayan, Alka Yagnik", album: "Raja Hindustani", cover: "https://i.ytimg.com/vi/wV8njoRVefQ/hqdefault.jpg" },
      { youtubeId: "W5lusYuAW0s", title: "Pardesi Pardesi", artist: "Udit Narayan, Alka Yagnik", album: "Raja Hindustani", cover: "https://i.ytimg.com/vi/W5lusYuAW0s/hqdefault.jpg" },
      { youtubeId: "IsPOtygII-Q", title: "Bholi Si Surat", artist: "Udit Narayan, Lata Mangeshkar", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/IsPOtygII-Q/hqdefault.jpg" },
      { youtubeId: "DIAcdeG70IE", title: "Chand Taare", artist: "Abhijeet", album: "Yes Boss", cover: "https://i.ytimg.com/vi/DIAcdeG70IE/hqdefault.jpg" },
      { youtubeId: "ojCnlV1MA-k", title: "Dil To Pagal Hai", artist: "Lata Mangeshkar, Udit Narayan", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/ojCnlV1MA-k/hqdefault.jpg" },
      { youtubeId: "5SvIuD6wJRI", title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", album: "Pardes", cover: "https://i.ytimg.com/vi/5SvIuD6wJRI/hqdefault.jpg" },
      { youtubeId: "RiUMVPpk0Fo", title: "Duniya Haseeno Ka Mela", artist: "Udit Narayan", album: "Gupt", cover: "https://i.ytimg.com/vi/RiUMVPpk0Fo/hqdefault.jpg" },
      { youtubeId: "VHQ0w-9ITBI", title: "I Love My India", artist: "Hariharan, Kavita Krishnamurthy, Shankar Mahadevan", album: "Pardes", cover: "https://i.ytimg.com/vi/VHQ0w-9ITBI/hqdefault.jpg" },
      { youtubeId: "oodOj8jx8ds", title: "Ke Ghar Kab Aaoge", artist: "Sonu Nigam, Roop Kumar Rathod", album: "Border", cover: "https://i.ytimg.com/vi/oodOj8jx8ds/hqdefault.jpg" },
      { youtubeId: "dGZb1kv5zW0", title: "Le Gayi", artist: "Asha Bhosle", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/dGZb1kv5zW0/hqdefault.jpg" },
      { youtubeId: "KUjswKk5vuM", title: "Yeh Dil Deewana", artist: "Sonu Nigam, Hema Sardesai", album: "Pardes", cover: "https://i.ytimg.com/vi/KUjswKk5vuM/hqdefault.jpg" },
      { youtubeId: "TdUu05Svkl8", title: "Ae Ajnabi", artist: "Udit Narayan, Mahalakshmi Iyer", album: "Dil Se..", cover: "https://i.ytimg.com/vi/TdUu05Svkl8/hqdefault.jpg" },
      { youtubeId: "FBdqEtxQpaY", title: "Gali Mein Aaj Chand Nikla", artist: "Alka Yagnik", album: "Zakhm", cover: "https://i.ytimg.com/vi/FBdqEtxQpaY/hqdefault.jpg" },
      { youtubeId: "OClXVLsI4jM", title: "Satrangi Re", artist: "Sonu Nigam, Kavita Krishnamurthy", album: "Dil Se..", cover: "https://i.ytimg.com/vi/OClXVLsI4jM/hqdefault.jpg" },
      { youtubeId: "HeFM4VFZL1M", title: "Tujhe Yaad Na Meri Aayee", artist: "Udit Narayan, Alka Yagnik, Manpreet Akhtar", album: "Kuch Kuch Hota Hai", cover: "https://i.ytimg.com/vi/HeFM4VFZL1M/hqdefault.jpg" },
      { youtubeId: "k2GtZBGt7ZI", title: "Chaha Hai Tujhko", artist: "Udit Narayan, Anuradha Paudwal", album: "Mann", cover: "https://i.ytimg.com/vi/k2GtZBGt7ZI/hqdefault.jpg" },
      { youtubeId: "SqZbGOCuai4", title: "Ishq Bina", artist: "Sonu Nigam, Anuradha Sriram, Sujatha Mohan", album: "Taal", cover: "https://i.ytimg.com/vi/SqZbGOCuai4/hqdefault.jpg" },
      { youtubeId: "rjtUQAz2KsU", title: "Taal Se Taal Mila", artist: "Udit Narayan, Alka Yagnik", album: "Taal", cover: "https://i.ytimg.com/vi/rjtUQAz2KsU/hqdefault.jpg" },
      { youtubeId: "KwiDJclWo44", title: "Tadap Tadap Ke", artist: "KK", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/KwiDJclWo44/hqdefault.jpg" },
    ],
  },
  {
    id: "saloon-classics",
    name: "Saloon Classics",
    hindiName: "सैलून क्लासिक्स",
    slot: "09:00–18:00 IST",
    description: "Every small-town barbershop rotation: mid-tempo, melodic, nothing that startles a man holding a razor.",
    sourceUrl: "https://www.deluxesaloon.space/playlists/saloon-classics",
    tracks: [
      { youtubeId: "KeyfUuXPOcY", title: "Dheere Dheere Se Meri Zindagi", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/KeyfUuXPOcY/hqdefault.jpg" },
      { youtubeId: "htMvfOfixuM", title: "Ek Ladki Ko Dekha To Aisa Laga", artist: "Kumar Sanu", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/htMvfOfixuM/hqdefault.jpg" },
      { youtubeId: "ZYotlBxpM3Q", title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam", album: "Jo Jeeta Wohi Sikandar", cover: "https://i.ytimg.com/vi/ZYotlBxpM3Q/hqdefault.jpg" },
      { youtubeId: "xdCObwkw8yE", title: "Tujhe Dekha To Ye Jaana Sanam", artist: "Kumar Sanu, Lata Mangeshkar", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/xdCObwkw8yE/hqdefault.jpg" },
      { youtubeId: "thjRNwjmAdQ", title: "Tumse Milne Ki Tamanna", artist: "S. P. Balasubrahmanyam", album: "Saajan", cover: "https://i.ytimg.com/vi/thjRNwjmAdQ/hqdefault.jpg" },
      { youtubeId: "8XtXLVylOoU", title: "Kuch Kuch Hota Hai", artist: "Udit Narayan, Alka Yagnik", album: "Kuch Kuch Hota Hai", cover: "https://i.ytimg.com/vi/8XtXLVylOoU/hqdefault.jpg" },
      { youtubeId: "SR3tmuLEPDw", title: "Aisi Deewangi", artist: "Kumar Sanu, Alka Yagnik", album: "Deewana", cover: "https://i.ytimg.com/vi/SR3tmuLEPDw/hqdefault.jpg" },
      { youtubeId: "1eSG6dLiYxY", title: "Churake Dil Mera", artist: "Kumar Sanu, Alka Yagnik", album: "Main Khiladi Tu Anari", cover: "https://i.ytimg.com/vi/1eSG6dLiYxY/hqdefault.jpg" },
      { youtubeId: "9u-r5W4WVO4", title: "Tip Tip Barsa Paani", artist: "Udit Narayan, Alka Yagnik", album: "Mohra", cover: "https://i.ytimg.com/vi/9u-r5W4WVO4/hqdefault.jpg" },
      { youtubeId: "nMpuAxFfqKg", title: "Yeh Kaali Kaali Aankhen", artist: "Kumar Sanu, Anu Malik", album: "Baazigar", cover: "https://i.ytimg.com/vi/nMpuAxFfqKg/hqdefault.jpg" },
      { youtubeId: "qEFgYftu29c", title: "Aankhon Se Tune Ye Kya Keh Diya", artist: "Kumar Sanu, Alka Yagnik", album: "Ghulam", cover: "https://i.ytimg.com/vi/qEFgYftu29c/hqdefault.jpg" },
      { youtubeId: "yexZf8g_dJw", title: "Chitthi Aayi Hai", artist: "Pankaj Udhas", album: "Naam", cover: "https://i.ytimg.com/vi/yexZf8g_dJw/hqdefault.jpg" },
      { youtubeId: "_IcVb6hFhPs", title: "Ghar Se Nikalte Hi", artist: "Udit Narayan", album: "Papa Kehte Hain", cover: "https://i.ytimg.com/vi/_IcVb6hFhPs/hqdefault.jpg" },
      { youtubeId: "YczkDMTaek4", title: "Sandese Aate Hain", artist: "Sonu Nigam, Roop Kumar Rathod", album: "Border", cover: "https://i.ytimg.com/vi/YczkDMTaek4/hqdefault.jpg" },
      { youtubeId: "As9DnNT3XZA", title: "Akele Hain To Kya Gham Hai", artist: "Udit Narayan, Alka Yagnik", album: "Qayamat Se Qayamat Tak", cover: "https://i.ytimg.com/vi/As9DnNT3XZA/hqdefault.jpg" },
      { youtubeId: "FEvBiayarlc", title: "Papa Kehte Hain", artist: "Udit Narayan", album: "Qayamat Se Qayamat Tak", cover: "https://i.ytimg.com/vi/FEvBiayarlc/hqdefault.jpg" },
      { youtubeId: "PhkADyPektU", title: "Aate Jaate Haste Gaate", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/PhkADyPektU/hqdefault.jpg" },
      { youtubeId: "6Pq4tBP3VV8", title: "Dil Deewana", artist: "Lata Mangeshkar", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/6Pq4tBP3VV8/hqdefault.jpg" },
      { youtubeId: "a1tVvBxs4rk", title: "Kabootar Ja Ja", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/a1tVvBxs4rk/hqdefault.jpg" },
      { youtubeId: "7kUlQYMg_l4", title: "Jaane Jigar Jaaneman", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/7kUlQYMg_l4/hqdefault.jpg" },
      { youtubeId: "uNt18l9UfjE", title: "Nazar Ke Samne", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/uNt18l9UfjE/hqdefault.jpg" },
      { youtubeId: "6ITANAYfvQ0", title: "Dekha Hai Pehli Baar", artist: "S. P. Balasubrahmanyam, Alka Yagnik", album: "Saajan", cover: "https://i.ytimg.com/vi/6ITANAYfvQ0/hqdefault.jpg" },
      { youtubeId: "W49bb08RErg", title: "Jaadu Bhari Aankhon Wali", artist: "Kumar Sanu, Alka Yagnik", album: "Phool Aur Kaante", cover: "https://i.ytimg.com/vi/W49bb08RErg/hqdefault.jpg" },
      { youtubeId: "BplOYQpyXZA", title: "Saathiya Tune Kya Kiya", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Love", cover: "https://i.ytimg.com/vi/BplOYQpyXZA/hqdefault.jpg" },
      { youtubeId: "3eBwrVPqJ8I", title: "Roja Jaaneman", artist: "Hariharan", album: "Roja", cover: "https://i.ytimg.com/vi/3eBwrVPqJ8I/hqdefault.jpg" },
      { youtubeId: "TSHxfQd1mlk", title: "Teri Ummeed Tera Intezar", artist: "Kumar Sanu, Sadhana Sargam", album: "Deewana", cover: "https://i.ytimg.com/vi/TSHxfQd1mlk/hqdefault.jpg" },
      { youtubeId: "pYDbGCEUN40", title: "Yeh Haseen Vadiyan", artist: "S. P. Balasubrahmanyam, K. S. Chithra", album: "Roja", cover: "https://i.ytimg.com/vi/pYDbGCEUN40/hqdefault.jpg" },
      { youtubeId: "ENw9BOvLkMk", title: "Aaja Sajan Aaja", artist: "Alka Yagnik", album: "Khal Nayak", cover: "https://i.ytimg.com/vi/ENw9BOvLkMk/hqdefault.jpg" },
      { youtubeId: "Cn3FAEQMnO4", title: "Baazigar O Baazigar", artist: "Kumar Sanu, Alka Yagnik", album: "Baazigar", cover: "https://i.ytimg.com/vi/Cn3FAEQMnO4/hqdefault.jpg" },
      { youtubeId: "0cUwFNGkLb8", title: "Ghunghat Ki Aad Se", artist: "Kumar Sanu, Alka Yagnik", album: "Hum Hain Rahi Pyar Ke", cover: "https://i.ytimg.com/vi/0cUwFNGkLb8/hqdefault.jpg" },
      { youtubeId: "jiEmpS_h77g", title: "Tu Mere Samne", artist: "Lata Mangeshkar, Udit Narayan", album: "Darr", cover: "https://i.ytimg.com/vi/jiEmpS_h77g/hqdefault.jpg" },
      { youtubeId: "4bIQNbHofs0", title: "Deewana Dil Deewana", artist: "Kumar Sanu, Alka Yagnik, Udit Narayan", album: "Kabhi Haan Kabhi Naa", cover: "https://i.ytimg.com/vi/4bIQNbHofs0/hqdefault.jpg" },
      { youtubeId: "KXkmrco12hI", title: "Pehla Pehla Pyar Hai", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/KXkmrco12hI/hqdefault.jpg" },
      { youtubeId: "goidtvB-O54", title: "Pyar Hua Chupke Se", artist: "Kavita Krishnamurthy", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/goidtvB-O54/hqdefault.jpg" },
      { youtubeId: "vYGPudMvxvI", title: "Raah Mein Unse Mulaqat", artist: "Kumar Sanu, Alka Yagnik", album: "Vijaypath", cover: "https://i.ytimg.com/vi/vYGPudMvxvI/hqdefault.jpg" },
      { youtubeId: "Qq-qu2PNuKg", title: "Rim Jhim Rim Jhim", artist: "Kumar Sanu, Kavita Krishnamurthy", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/Qq-qu2PNuKg/hqdefault.jpg" },
      { youtubeId: "0UJbl8H3_No", title: "Yeh Mausam Ka Jadoo", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/0UJbl8H3_No/hqdefault.jpg" },
      { youtubeId: "5w85_aCzf0o", title: "Aankhon Mein Base Ho Tum", artist: "Kavita Krishnamurthy, Kumar Sanu", album: "Takkar", cover: "https://i.ytimg.com/vi/5w85_aCzf0o/hqdefault.jpg" },
      { youtubeId: "dHzSmJGSnIc", title: "Akhiyaan Milaoon Kabhi", artist: "Udit Narayan, Alka Yagnik", album: "Raja", cover: "https://i.ytimg.com/vi/dHzSmJGSnIc/hqdefault.jpg" },
      { youtubeId: "hw_HpTI_Wkw", title: "Ho Gaya Hai Tujhko To Pyar Sajna", artist: "Lata Mangeshkar, Udit Narayan", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/hw_HpTI_Wkw/hqdefault.jpg" },
      { youtubeId: "_YB1taxJPgk", title: "Kehna Hi Kya", artist: "K. S. Chithra", album: "Bombay", cover: "https://i.ytimg.com/vi/_YB1taxJPgk/hqdefault.jpg" },
      { youtubeId: "s1LozokQjIg", title: "Mere Khwabon Mein Jo Aaye", artist: "Lata Mangeshkar", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/s1LozokQjIg/hqdefault.jpg" },
      { youtubeId: "t5JSLRB9ZAU", title: "Raja Ko Rani Se Pyar Ho Gaya", artist: "Udit Narayan, Kavita Krishnamurthy", album: "Akele Hum Akele Tum", cover: "https://i.ytimg.com/vi/t5JSLRB9ZAU/hqdefault.jpg" },
      { youtubeId: "nqTS7ngviwQ", title: "Tu Mile Dil Khile", artist: "Kumar Sanu, Alka Yagnik", album: "Criminal", cover: "https://i.ytimg.com/vi/nqTS7ngviwQ/hqdefault.jpg" },
      { youtubeId: "96YVQBjrtWE", title: "Zara Sa Jhoom Loon Main", artist: "Abhijeet, Asha Bhosle", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/96YVQBjrtWE/hqdefault.jpg" },
      { youtubeId: "6C34aCdjJtM", title: "Jhanjhariya", artist: "Kumar Sanu, Alka Yagnik", album: "Krishna", cover: "https://i.ytimg.com/vi/6C34aCdjJtM/hqdefault.jpg" },
      { youtubeId: "wV8njoRVefQ", title: "Kitna Pyara Tujhe Rab Ne Banaya", artist: "Udit Narayan, Alka Yagnik", album: "Raja Hindustani", cover: "https://i.ytimg.com/vi/wV8njoRVefQ/hqdefault.jpg" },
      { youtubeId: "OEpFiDKqH7E", title: "Are Re Are", artist: "Udit Narayan, Lata Mangeshkar", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/OEpFiDKqH7E/hqdefault.jpg" },
      { youtubeId: "DIAcdeG70IE", title: "Chand Taare", artist: "Abhijeet", album: "Yes Boss", cover: "https://i.ytimg.com/vi/DIAcdeG70IE/hqdefault.jpg" },
      { youtubeId: "ojCnlV1MA-k", title: "Dil To Pagal Hai", artist: "Lata Mangeshkar, Udit Narayan", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/ojCnlV1MA-k/hqdefault.jpg" },
      { youtubeId: "GAgdtaZjkNI", title: "Main Koi Aisa Geet Gaoon", artist: "Abhijeet, Alka Yagnik", album: "Yes Boss", cover: "https://i.ytimg.com/vi/GAgdtaZjkNI/hqdefault.jpg" },
      { youtubeId: "WkfcHsPKwds", title: "Meri Mehbooba", artist: "Kumar Sanu, Alka Yagnik", album: "Pardes", cover: "https://i.ytimg.com/vi/WkfcHsPKwds/hqdefault.jpg" },
      { youtubeId: "gCcGXy_Mv8g", title: "Neend Churai Meri", artist: "Kumar Sanu, Alka Yagnik", album: "Ishq", cover: "https://i.ytimg.com/vi/gCcGXy_Mv8g/hqdefault.jpg" },
      { youtubeId: "M-2nlaOQQSQ", title: "Jiya Jale", artist: "Lata Mangeshkar, M. G. Sreekumar", album: "Dil Se..", cover: "https://i.ytimg.com/vi/M-2nlaOQQSQ/hqdefault.jpg" },
      { youtubeId: "oJcE_QPFAng", title: "Ladki Badi Anjani Hai", artist: "Kumar Sanu, Alka Yagnik", album: "Kuch Kuch Hota Hai", cover: "https://i.ytimg.com/vi/oJcE_QPFAng/hqdefault.jpg" },
      { youtubeId: "7k5gM4ClRRo", title: "Aankhon Ki Gustakhiyan", artist: "Kumar Sanu, Kavita Krishnamurthy", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/7k5gM4ClRRo/hqdefault.jpg" },
      { youtubeId: "MCXQXuKpgKE", title: "Albela Sajan", artist: "Ustad Sultan Khan, Kavita Krishnamurthy, Shankar Mahadevan", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/MCXQXuKpgKE/hqdefault.jpg" },
      { youtubeId: "2knQOXevwKE", title: "Chand Chupa Badal Mein", artist: "Udit Narayan, Alka Yagnik", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/2knQOXevwKE/hqdefault.jpg" },
      { youtubeId: "Tfjoyp0g5HA", title: "Dholi Taro Dhol Baaje", artist: "Vinod Rathod, Karsan Sagathia, Kavita Krishnamurthy", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/Tfjoyp0g5HA/hqdefault.jpg" },
      { youtubeId: "MvcNeQlqtes", title: "Dil Ne Yeh Kaha Hai Dil Se", artist: "Udit Narayan, Alka Yagnik", album: "Dhadkan", cover: "https://i.ytimg.com/vi/MvcNeQlqtes/hqdefault.jpg" },
    ],
  },
  {
    id: "dard-90s",
    name: "90s Dard",
    hindiName: "नब्बे का दर्द",
    slot: "18:00–22:00 IST",
    description: "The sad half of the decade — slow, nasal, unembarrassed, and completely undefeated.",
    sourceUrl: "https://www.deluxesaloon.space/playlists/dard-90s",
    tracks: [
      { youtubeId: "rTatsmUgmiA", title: "Ab Tere Bin Jee Lenge Hum", artist: "Kumar Sanu", album: "Aashiqui", cover: "https://i.ytimg.com/vi/rTatsmUgmiA/hqdefault.jpg" },
      { youtubeId: "PUGaSHPdTGg", title: "Sochenge Tumhe Pyar", artist: "Kumar Sanu", album: "Deewana", cover: "https://i.ytimg.com/vi/PUGaSHPdTGg/hqdefault.jpg" },
      { youtubeId: "thjRNwjmAdQ", title: "Tumse Milne Ki Tamanna", artist: "S. P. Balasubrahmanyam", album: "Saajan", cover: "https://i.ytimg.com/vi/thjRNwjmAdQ/hqdefault.jpg" },
      { youtubeId: "iupGwQqjgOk", title: "Bahut Pyar Karte Hain", artist: "Anuradha Paudwal, S. P. Balasubrahmanyam", album: "Saajan", cover: "https://i.ytimg.com/vi/iupGwQqjgOk/hqdefault.jpg" },
      { youtubeId: "Kidtrrn4aUM", title: "Kuch Na Kaho", artist: "Kumar Sanu", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/Kidtrrn4aUM/hqdefault.jpg" },
      { youtubeId: "FD3vgLOEdgk", title: "Jaadu Teri Nazar", artist: "Udit Narayan", album: "Darr", cover: "https://i.ytimg.com/vi/FD3vgLOEdgk/hqdefault.jpg" },
      { youtubeId: "KeyfUuXPOcY", title: "Dheere Dheere Se Meri Zindagi", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/KeyfUuXPOcY/hqdefault.jpg" },
      { youtubeId: "htMvfOfixuM", title: "Ek Ladki Ko Dekha To Aisa Laga", artist: "Kumar Sanu", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/htMvfOfixuM/hqdefault.jpg" },
      { youtubeId: "qEFgYftu29c", title: "Aankhon Se Tune Ye Kya Keh Diya", artist: "Kumar Sanu, Alka Yagnik", album: "Ghulam", cover: "https://i.ytimg.com/vi/qEFgYftu29c/hqdefault.jpg" },
      { youtubeId: "l7iTcZ__Ejg", title: "Jaati Hoon Main", artist: "Kumar Sanu, Alka Yagnik", album: "Karan Arjun", cover: "https://i.ytimg.com/vi/l7iTcZ__Ejg/hqdefault.jpg" },
      { youtubeId: "70YFS4GvuQ0", title: "Chhod Aaye Hum Woh Galiyan", artist: "Hariharan, Suresh Wadkar, K. S. Chithra, Vinod Sehgal", album: "Maachis", cover: "https://i.ytimg.com/vi/70YFS4GvuQ0/hqdefault.jpg" },
      { youtubeId: "EhOQvAe6bfM", title: "Jab Koi Baat Bigad Jaye", artist: "Kumar Sanu, Sadhana Sargam", album: "Jurm", cover: "https://i.ytimg.com/vi/EhOQvAe6bfM/hqdefault.jpg" },
      { youtubeId: "sWqjZpBtcxc", title: "Ae Mere Humsafar", artist: "Udit Narayan, Alka Yagnik", album: "Qayamat Se Qayamat Tak", cover: "https://i.ytimg.com/vi/sWqjZpBtcxc/hqdefault.jpg" },
      { youtubeId: "6Pq4tBP3VV8", title: "Dil Deewana", artist: "Lata Mangeshkar", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/6Pq4tBP3VV8/hqdefault.jpg" },
      { youtubeId: "BkLOBuTAtS0", title: "Mere Rang Mein Rangne Wali", artist: "S. P. Balasubrahmanyam", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/BkLOBuTAtS0/hqdefault.jpg" },
      { youtubeId: "fBylcT-TWZw", title: "Bas Ek Sanam Chahiye", artist: "Kumar Sanu", album: "Aashiqui", cover: "https://i.ytimg.com/vi/fBylcT-TWZw/hqdefault.jpg" },
      { youtubeId: "7kUlQYMg_l4", title: "Jaane Jigar Jaaneman", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/7kUlQYMg_l4/hqdefault.jpg" },
      { youtubeId: "otQmzlm-s7Q", title: "Main Duniya Bhula Doonga", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/otQmzlm-s7Q/hqdefault.jpg" },
      { youtubeId: "uNt18l9UfjE", title: "Nazar Ke Samne", artist: "Kumar Sanu, Anuradha Paudwal", album: "Aashiqui", cover: "https://i.ytimg.com/vi/uNt18l9UfjE/hqdefault.jpg" },
      { youtubeId: "YCuhzjK11iA", title: "Saanson Ki Zaroorat Hai Jaise", artist: "Kumar Sanu", album: "Aashiqui", cover: "https://i.ytimg.com/vi/YCuhzjK11iA/hqdefault.jpg" },
      { youtubeId: "FsNc7I33w60", title: "Mera Dil Bhi Kitna Pagal Hai", artist: "S. P. Balasubrahmanyam, Alka Yagnik", album: "Saajan", cover: "https://i.ytimg.com/vi/FsNc7I33w60/hqdefault.jpg" },
      { youtubeId: "3eBwrVPqJ8I", title: "Roja Jaaneman", artist: "Hariharan", album: "Roja", cover: "https://i.ytimg.com/vi/3eBwrVPqJ8I/hqdefault.jpg" },
      { youtubeId: "TSHxfQd1mlk", title: "Teri Ummeed Tera Intezar", artist: "Kumar Sanu, Sadhana Sargam", album: "Deewana", cover: "https://i.ytimg.com/vi/TSHxfQd1mlk/hqdefault.jpg" },
      { youtubeId: "ENw9BOvLkMk", title: "Aaja Sajan Aaja", artist: "Alka Yagnik", album: "Khal Nayak", cover: "https://i.ytimg.com/vi/ENw9BOvLkMk/hqdefault.jpg" },
      { youtubeId: "fg9G1dacXjk", title: "Chhupana Bhi Nahi Aata", artist: "Vinod Rathod", album: "Baazigar", cover: "https://i.ytimg.com/vi/fg9G1dacXjk/hqdefault.jpg" },
      { youtubeId: "708MrJ6ZJsI", title: "Kitaben Bahut Si", artist: "Kumar Sanu, Asha Bhosle", album: "Baazigar", cover: "https://i.ytimg.com/vi/708MrJ6ZJsI/hqdefault.jpg" },
      { youtubeId: "tfSqvusJiFI", title: "Likha Hai Teri Aankhon Mein", artist: "Kumar Sanu, Lata Mangeshkar", album: "Darr", cover: "https://i.ytimg.com/vi/tfSqvusJiFI/hqdefault.jpg" },
      { youtubeId: "7egtbySpvfw", title: "Ae Kaash Ke Hum", artist: "Kumar Sanu", album: "Kabhi Haan Kabhi Naa", cover: "https://i.ytimg.com/vi/7egtbySpvfw/hqdefault.jpg" },
      { youtubeId: "T7IZuj5fvYM", title: "Is Tarah Aashiqui Ka", artist: "Kumar Sanu", album: "Imtihan", cover: "https://i.ytimg.com/vi/T7IZuj5fvYM/hqdefault.jpg" },
      { youtubeId: "nopOmxeaCLA", title: "Lo Chali Main", artist: "Lata Mangeshkar", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/nopOmxeaCLA/hqdefault.jpg" },
      { youtubeId: "LmagwQ8fp3Q", title: "Maine Pyar Tumhi Se Kiya Hai", artist: "Kumar Sanu, Alka Yagnik", album: "Main Khiladi Tu Anari", cover: "https://i.ytimg.com/vi/LmagwQ8fp3Q/hqdefault.jpg" },
      { youtubeId: "fPbDOCBx11w", title: "Na Kajre Ki Dhaar", artist: "Pankaj Udhas, Sadhana Sargam", album: "Mohra", cover: "https://i.ytimg.com/vi/fPbDOCBx11w/hqdefault.jpg" },
      { youtubeId: "goidtvB-O54", title: "Pyar Hua Chupke Se", artist: "Kavita Krishnamurthy", album: "1942: A Love Story", cover: "https://i.ytimg.com/vi/goidtvB-O54/hqdefault.jpg" },
      { youtubeId: "5w85_aCzf0o", title: "Aankhon Mein Base Ho Tum", artist: "Kavita Krishnamurthy, Kumar Sanu", album: "Takkar", cover: "https://i.ytimg.com/vi/5w85_aCzf0o/hqdefault.jpg" },
      { youtubeId: "3z7tf28mR90", title: "Aisa Zakhm Diya Hai", artist: "Kumar Sanu", album: "Akele Hum Akele Tum", cover: "https://i.ytimg.com/vi/3z7tf28mR90/hqdefault.jpg" },
      { youtubeId: "mSu5cz2GFts", title: "Dil Mera Churaya Kyun", artist: "Kumar Sanu", album: "Akele Hum Akele Tum", cover: "https://i.ytimg.com/vi/mSu5cz2GFts/hqdefault.jpg" },
      { youtubeId: "11v9ALkOiio", title: "Hai Rama", artist: "Hariharan, Swarnalatha", album: "Rangeela", cover: "https://i.ytimg.com/vi/11v9ALkOiio/hqdefault.jpg" },
      { youtubeId: "hw_HpTI_Wkw", title: "Ho Gaya Hai Tujhko To Pyar Sajna", artist: "Lata Mangeshkar, Udit Narayan", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/hw_HpTI_Wkw/hqdefault.jpg" },
      { youtubeId: "_YB1taxJPgk", title: "Kehna Hi Kya", artist: "K. S. Chithra", album: "Bombay", cover: "https://i.ytimg.com/vi/_YB1taxJPgk/hqdefault.jpg" },
      { youtubeId: "YdmHOtMM8Yc", title: "Nazrein Mili Dil Dhadka", artist: "Udit Narayan, Alka Yagnik", album: "Raja", cover: "https://i.ytimg.com/vi/YdmHOtMM8Yc/hqdefault.jpg" },
      { youtubeId: "waTwDgK2tkk", title: "Tu Hi Re", artist: "Hariharan, Kavita Krishnamurthy", album: "Bombay", cover: "https://i.ytimg.com/vi/waTwDgK2tkk/hqdefault.jpg" },
      { youtubeId: "nqTS7ngviwQ", title: "Tu Mile Dil Khile", artist: "Kumar Sanu, Alka Yagnik", album: "Criminal", cover: "https://i.ytimg.com/vi/nqTS7ngviwQ/hqdefault.jpg" },
      { youtubeId: "vIyNwuPTafk", title: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan", album: "Raja Hindustani", cover: "https://i.ytimg.com/vi/vIyNwuPTafk/hqdefault.jpg" },
      { youtubeId: "0vXTVXM6HEE", title: "Ho Nahi Sakta", artist: "Kumar Sanu", album: "Diljale", cover: "https://i.ytimg.com/vi/0vXTVXM6HEE/hqdefault.jpg" },
      { youtubeId: "W5lusYuAW0s", title: "Pardesi Pardesi", artist: "Udit Narayan, Alka Yagnik", album: "Raja Hindustani", cover: "https://i.ytimg.com/vi/W5lusYuAW0s/hqdefault.jpg" },
      { youtubeId: "IsPOtygII-Q", title: "Bholi Si Surat", artist: "Udit Narayan, Lata Mangeshkar", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/IsPOtygII-Q/hqdefault.jpg" },
      { youtubeId: "5SvIuD6wJRI", title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", album: "Pardes", cover: "https://i.ytimg.com/vi/5SvIuD6wJRI/hqdefault.jpg" },
      { youtubeId: "oodOj8jx8ds", title: "Ke Ghar Kab Aaoge", artist: "Sonu Nigam, Roop Kumar Rathod", album: "Border", cover: "https://i.ytimg.com/vi/oodOj8jx8ds/hqdefault.jpg" },
      { youtubeId: "dGZb1kv5zW0", title: "Le Gayi", artist: "Asha Bhosle", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/dGZb1kv5zW0/hqdefault.jpg" },
      { youtubeId: "WkfcHsPKwds", title: "Meri Mehbooba", artist: "Kumar Sanu, Alka Yagnik", album: "Pardes", cover: "https://i.ytimg.com/vi/WkfcHsPKwds/hqdefault.jpg" },
      { youtubeId: "TdUu05Svkl8", title: "Ae Ajnabi", artist: "Udit Narayan, Mahalakshmi Iyer", album: "Dil Se..", cover: "https://i.ytimg.com/vi/TdUu05Svkl8/hqdefault.jpg" },
      { youtubeId: "FBdqEtxQpaY", title: "Gali Mein Aaj Chand Nikla", artist: "Alka Yagnik", album: "Zakhm", cover: "https://i.ytimg.com/vi/FBdqEtxQpaY/hqdefault.jpg" },
      { youtubeId: "M-2nlaOQQSQ", title: "Jiya Jale", artist: "Lata Mangeshkar, M. G. Sreekumar", album: "Dil Se..", cover: "https://i.ytimg.com/vi/M-2nlaOQQSQ/hqdefault.jpg" },
      { youtubeId: "OClXVLsI4jM", title: "Satrangi Re", artist: "Sonu Nigam, Kavita Krishnamurthy", album: "Dil Se..", cover: "https://i.ytimg.com/vi/OClXVLsI4jM/hqdefault.jpg" },
      { youtubeId: "HeFM4VFZL1M", title: "Tujhe Yaad Na Meri Aayee", artist: "Udit Narayan, Alka Yagnik, Manpreet Akhtar", album: "Kuch Kuch Hota Hai", cover: "https://i.ytimg.com/vi/HeFM4VFZL1M/hqdefault.jpg" },
      { youtubeId: "7k5gM4ClRRo", title: "Aankhon Ki Gustakhiyan", artist: "Kumar Sanu, Kavita Krishnamurthy", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/7k5gM4ClRRo/hqdefault.jpg" },
      { youtubeId: "k2GtZBGt7ZI", title: "Chaha Hai Tujhko", artist: "Udit Narayan, Anuradha Paudwal", album: "Mann", cover: "https://i.ytimg.com/vi/k2GtZBGt7ZI/hqdefault.jpg" },
      { youtubeId: "K38OA13ZBiY", title: "Maiyya Yashoda", artist: "Alka Yagnik, Kavita Krishnamurthy, Anuradha Paudwal", album: "Hum Saath-Saath Hain", cover: "https://i.ytimg.com/vi/K38OA13ZBiY/hqdefault.jpg" },
      { youtubeId: "KwiDJclWo44", title: "Tadap Tadap Ke", artist: "KK", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/KwiDJclWo44/hqdefault.jpg" },
      { youtubeId: "MvcNeQlqtes", title: "Dil Ne Yeh Kaha Hai Dil Se", artist: "Udit Narayan, Alka Yagnik", album: "Dhadkan", cover: "https://i.ytimg.com/vi/MvcNeQlqtes/hqdefault.jpg" },
    ],
  },
  {
    id: "shaadi-sunday",
    name: "Shaadi & Sunday",
    hindiName: "शादी और इतवार",
    slot: "05:00–09:00 IST",
    description: "The other side of the decade — Anu Malik, Viju Shah and a great deal of gated reverb.",
    sourceUrl: "https://www.deluxesaloon.space/playlists/shaadi-sunday",
    tracks: [
      { youtubeId: "fT4vP4PnLxg", title: "Tu Cheez Badi Hai Mast Mast", artist: "Udit Narayan, Kavita Krishnamurthy", album: "Mohra", cover: "https://i.ytimg.com/vi/fT4vP4PnLxg/hqdefault.jpg" },
      { youtubeId: "QmHTmr8Kazs", title: "Oonchi Hai Building", artist: "Abhijeet, Poornima", album: "Judwaa", cover: "https://i.ytimg.com/vi/QmHTmr8Kazs/hqdefault.jpg" },
      { youtubeId: "BJrHJoCqJKo", title: "Dilbar Dilbar", artist: "Alka Yagnik", album: "Sirf Tum", cover: "https://i.ytimg.com/vi/BJrHJoCqJKo/hqdefault.jpg" },
      { youtubeId: "ZqcDGvCM_w0", title: "Didi Tera Devar Deewana", artist: "Lata Mangeshkar, S. P. Balasubrahmanyam", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/ZqcDGvCM_w0/hqdefault.jpg" },
      { youtubeId: "1eSG6dLiYxY", title: "Churake Dil Mera", artist: "Kumar Sanu, Alka Yagnik", album: "Main Khiladi Tu Anari", cover: "https://i.ytimg.com/vi/1eSG6dLiYxY/hqdefault.jpg" },
      { youtubeId: "nMpuAxFfqKg", title: "Yeh Kaali Kaali Aankhen", artist: "Kumar Sanu, Anu Malik", album: "Baazigar", cover: "https://i.ytimg.com/vi/nMpuAxFfqKg/hqdefault.jpg" },
      { youtubeId: "9u-r5W4WVO4", title: "Tip Tip Barsa Paani", artist: "Udit Narayan, Alka Yagnik", album: "Mohra", cover: "https://i.ytimg.com/vi/9u-r5W4WVO4/hqdefault.jpg" },
      { youtubeId: "SR3tmuLEPDw", title: "Aisi Deewangi", artist: "Kumar Sanu, Alka Yagnik", album: "Deewana", cover: "https://i.ytimg.com/vi/SR3tmuLEPDw/hqdefault.jpg" },
      { youtubeId: "jBpRItrod-Q", title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/jBpRItrod-Q/hqdefault.jpg" },
      { youtubeId: "lZLxjLYyhYQ", title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh, Sapna Awasthi", album: "Dil Se..", cover: "https://i.ytimg.com/vi/lZLxjLYyhYQ/hqdefault.jpg" },
      { youtubeId: "8XtXLVylOoU", title: "Kuch Kuch Hota Hai", artist: "Udit Narayan, Alka Yagnik", album: "Kuch Kuch Hota Hai", cover: "https://i.ytimg.com/vi/8XtXLVylOoU/hqdefault.jpg" },
      { youtubeId: "ZYotlBxpM3Q", title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam", album: "Jo Jeeta Wohi Sikandar", cover: "https://i.ytimg.com/vi/ZYotlBxpM3Q/hqdefault.jpg" },
      { youtubeId: "JzFemLoFkN4", title: "Ek Do Teen", artist: "Alka Yagnik", album: "Tezaab", cover: "https://i.ytimg.com/vi/JzFemLoFkN4/hqdefault.jpg" },
      { youtubeId: "FEvBiayarlc", title: "Papa Kehte Hain", artist: "Udit Narayan", album: "Qayamat Se Qayamat Tak", cover: "https://i.ytimg.com/vi/FEvBiayarlc/hqdefault.jpg" },
      { youtubeId: "YuYRQGZqGxE", title: "Tu Mera Janu Hai", artist: "Amit Kumar", album: "Hero Hiralal", cover: "https://i.ytimg.com/vi/YuYRQGZqGxE/hqdefault.jpg" },
      { youtubeId: "a1tVvBxs4rk", title: "Kabootar Ja Ja", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Maine Pyar Kiya", cover: "https://i.ytimg.com/vi/a1tVvBxs4rk/hqdefault.jpg" },
      { youtubeId: "GKHtybylaSM", title: "Oye Oye", artist: "Vijeta Pandit, Amit Kumar", album: "Tridev", cover: "https://i.ytimg.com/vi/GKHtybylaSM/hqdefault.jpg" },
      { youtubeId: "eYl9i8mH1lI", title: "Tirchi Topi Wale", artist: "Amit Kumar, Sadhana Sargam", album: "Tridev", cover: "https://i.ytimg.com/vi/eYl9i8mH1lI/hqdefault.jpg" },
      { youtubeId: "6ITANAYfvQ0", title: "Dekha Hai Pehli Baar", artist: "S. P. Balasubrahmanyam, Alka Yagnik", album: "Saajan", cover: "https://i.ytimg.com/vi/6ITANAYfvQ0/hqdefault.jpg" },
      { youtubeId: "W49bb08RErg", title: "Jaadu Bhari Aankhon Wali", artist: "Kumar Sanu, Alka Yagnik", album: "Phool Aur Kaante", cover: "https://i.ytimg.com/vi/W49bb08RErg/hqdefault.jpg" },
      { youtubeId: "ijGumwamEQU", title: "Jumma Chumma De De", artist: "Sudesh Bhosle, Kavita Krishnamurthy", album: "Hum", cover: "https://i.ytimg.com/vi/ijGumwamEQU/hqdefault.jpg" },
      { youtubeId: "BplOYQpyXZA", title: "Saathiya Tune Kya Kiya", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Love", cover: "https://i.ytimg.com/vi/BplOYQpyXZA/hqdefault.jpg" },
      { youtubeId: "P7i0Z4yDKNM", title: "Dhak Dhak Karne Laga", artist: "Anuradha Paudwal, Udit Narayan", album: "Beta", cover: "https://i.ytimg.com/vi/P7i0Z4yDKNM/hqdefault.jpg" },
      { youtubeId: "_T-NphgkgVc", title: "Koi Na Koi Chahiye", artist: "Kumar Sanu", album: "Deewana", cover: "https://i.ytimg.com/vi/_T-NphgkgVc/hqdefault.jpg" },
      { youtubeId: "3OXiqmUhB70", title: "Choli Ke Peeche", artist: "Ila Arun, Alka Yagnik", album: "Khal Nayak", cover: "https://i.ytimg.com/vi/3OXiqmUhB70/hqdefault.jpg" },
      { youtubeId: "0cUwFNGkLb8", title: "Ghunghat Ki Aad Se", artist: "Kumar Sanu, Alka Yagnik", album: "Hum Hain Rahi Pyar Ke", cover: "https://i.ytimg.com/vi/0cUwFNGkLb8/hqdefault.jpg" },
      { youtubeId: "Oj484P4OXD8", title: "Tu Mera Dil Tu Meri Jaan", artist: "Lata Mangeshkar, Udit Narayan", album: "Darr", cover: "https://i.ytimg.com/vi/Oj484P4OXD8/hqdefault.jpg" },
      { youtubeId: "jiEmpS_h77g", title: "Tu Mere Samne", artist: "Lata Mangeshkar, Udit Narayan", album: "Darr", cover: "https://i.ytimg.com/vi/jiEmpS_h77g/hqdefault.jpg" },
      { youtubeId: "4bIQNbHofs0", title: "Deewana Dil Deewana", artist: "Kumar Sanu, Alka Yagnik, Udit Narayan", album: "Kabhi Haan Kabhi Naa", cover: "https://i.ytimg.com/vi/4bIQNbHofs0/hqdefault.jpg" },
      { youtubeId: "Ua5AW2czRAE", title: "Maye Ni Maye", artist: "Lata Mangeshkar, S. P. Balasubrahmanyam", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/Ua5AW2czRAE/hqdefault.jpg" },
      { youtubeId: "KXkmrco12hI", title: "Pehla Pehla Pyar Hai", artist: "S. P. Balasubrahmanyam, Lata Mangeshkar", album: "Hum Aapke Hain Koun..!", cover: "https://i.ytimg.com/vi/KXkmrco12hI/hqdefault.jpg" },
      { youtubeId: "vYGPudMvxvI", title: "Raah Mein Unse Mulaqat", artist: "Kumar Sanu, Alka Yagnik", album: "Vijaypath", cover: "https://i.ytimg.com/vi/vYGPudMvxvI/hqdefault.jpg" },
      { youtubeId: "2tTxFyOS3Fo", title: "Humma Humma", artist: "Remo Fernandes, Swarnalatha", album: "Bombay", cover: "https://i.ytimg.com/vi/2tTxFyOS3Fo/hqdefault.jpg" },
      { youtubeId: "-bNwqXvMuB8", title: "Mehndi Laga Ke Rakhna", artist: "Udit Narayan, Lata Mangeshkar", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/-bNwqXvMuB8/hqdefault.jpg" },
      { youtubeId: "s1LozokQjIg", title: "Mere Khwabon Mein Jo Aaye", artist: "Lata Mangeshkar", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/s1LozokQjIg/hqdefault.jpg" },
      { youtubeId: "t5JSLRB9ZAU", title: "Raja Ko Rani Se Pyar Ho Gaya", artist: "Udit Narayan, Kavita Krishnamurthy", album: "Akele Hum Akele Tum", cover: "https://i.ytimg.com/vi/t5JSLRB9ZAU/hqdefault.jpg" },
      { youtubeId: "W1GNGlaFKYw", title: "Tanha Tanha", artist: "Asha Bhosle", album: "Rangeela", cover: "https://i.ytimg.com/vi/W1GNGlaFKYw/hqdefault.jpg" },
      { youtubeId: "xdCObwkw8yE", title: "Tujhe Dekha To Ye Jaana Sanam", artist: "Kumar Sanu, Lata Mangeshkar", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/xdCObwkw8yE/hqdefault.jpg" },
      { youtubeId: "96YVQBjrtWE", title: "Zara Sa Jhoom Loon Main", artist: "Abhijeet, Asha Bhosle", album: "Dilwale Dulhania Le Jayenge", cover: "https://i.ytimg.com/vi/96YVQBjrtWE/hqdefault.jpg" },
      { youtubeId: "6C34aCdjJtM", title: "Jhanjhariya", artist: "Kumar Sanu, Alka Yagnik", album: "Krishna", cover: "https://i.ytimg.com/vi/6C34aCdjJtM/hqdefault.jpg" },
      { youtubeId: "OEpFiDKqH7E", title: "Are Re Are", artist: "Udit Narayan, Lata Mangeshkar", album: "Dil To Pagal Hai", cover: "https://i.ytimg.com/vi/OEpFiDKqH7E/hqdefault.jpg" },
      { youtubeId: "RiUMVPpk0Fo", title: "Duniya Haseeno Ka Mela", artist: "Udit Narayan", album: "Gupt", cover: "https://i.ytimg.com/vi/RiUMVPpk0Fo/hqdefault.jpg" },
      { youtubeId: "VHQ0w-9ITBI", title: "I Love My India", artist: "Hariharan, Kavita Krishnamurthy, Shankar Mahadevan", album: "Pardes", cover: "https://i.ytimg.com/vi/VHQ0w-9ITBI/hqdefault.jpg" },
      { youtubeId: "GAgdtaZjkNI", title: "Main Koi Aisa Geet Gaoon", artist: "Abhijeet, Alka Yagnik", album: "Yes Boss", cover: "https://i.ytimg.com/vi/GAgdtaZjkNI/hqdefault.jpg" },
      { youtubeId: "gCcGXy_Mv8g", title: "Neend Churai Meri", artist: "Kumar Sanu, Alka Yagnik", album: "Ishq", cover: "https://i.ytimg.com/vi/gCcGXy_Mv8g/hqdefault.jpg" },
      { youtubeId: "4pIV63BLA6A", title: "Sona Kitna Sona Hai", artist: "Poornima, Vinod Rathod", album: "Hero No. 1", cover: "https://i.ytimg.com/vi/4pIV63BLA6A/hqdefault.jpg" },
      { youtubeId: "KUjswKk5vuM", title: "Yeh Dil Deewana", artist: "Sonu Nigam, Hema Sardesai", album: "Pardes", cover: "https://i.ytimg.com/vi/KUjswKk5vuM/hqdefault.jpg" },
      { youtubeId: "C5kihXiyHfE", title: "Aati Kya Khandala", artist: "Aamir Khan, Alka Yagnik", album: "Ghulam", cover: "https://i.ytimg.com/vi/C5kihXiyHfE/hqdefault.jpg" },
      { youtubeId: "TMEuO92RqD4", title: "Kisi Disco Mein Jaaye", artist: "Udit Narayan, Alka Yagnik", album: "Bade Miyan Chote Miyan", cover: "https://i.ytimg.com/vi/TMEuO92RqD4/hqdefault.jpg" },
      { youtubeId: "gmXlGQAg400", title: "Koi Mil Gaya", artist: "Udit Narayan, Alka Yagnik, Kavita Krishnamurthy", album: "Kuch Kuch Hota Hai", cover: "https://i.ytimg.com/vi/gmXlGQAg400/hqdefault.jpg" },
      { youtubeId: "oJcE_QPFAng", title: "Ladki Badi Anjani Hai", artist: "Kumar Sanu, Alka Yagnik", album: "Kuch Kuch Hota Hai", cover: "https://i.ytimg.com/vi/oJcE_QPFAng/hqdefault.jpg" },
      { youtubeId: "p-pQaTOmVrs", title: "Mere Mehboob Mere Sanam", artist: "Vinod Rathod, Alka Yagnik", album: "Duplicate", cover: "https://i.ytimg.com/vi/p-pQaTOmVrs/hqdefault.jpg" },
      { youtubeId: "MCXQXuKpgKE", title: "Albela Sajan", artist: "Ustad Sultan Khan, Kavita Krishnamurthy, Shankar Mahadevan", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/MCXQXuKpgKE/hqdefault.jpg" },
      { youtubeId: "2knQOXevwKE", title: "Chand Chupa Badal Mein", artist: "Udit Narayan, Alka Yagnik", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/2knQOXevwKE/hqdefault.jpg" },
      { youtubeId: "Tfjoyp0g5HA", title: "Dholi Taro Dhol Baaje", artist: "Vinod Rathod, Karsan Sagathia, Kavita Krishnamurthy", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/Tfjoyp0g5HA/hqdefault.jpg" },
      { youtubeId: "UuACNxa1R8A", title: "Ghungroo Toot Gaye", artist: "Kumar Sanu, Alka Yagnik", album: "Vaastav", cover: "https://i.ytimg.com/vi/UuACNxa1R8A/hqdefault.jpg" },
      { youtubeId: "K38OA13ZBiY", title: "Maiyya Yashoda", artist: "Alka Yagnik, Kavita Krishnamurthy, Anuradha Paudwal", album: "Hum Saath-Saath Hain", cover: "https://i.ytimg.com/vi/K38OA13ZBiY/hqdefault.jpg" },
      { youtubeId: "tcBK_zWgXpw", title: "Nimbooda", artist: "Kavita Krishnamurthy", album: "Hum Dil De Chuke Sanam", cover: "https://i.ytimg.com/vi/tcBK_zWgXpw/hqdefault.jpg" },
      { youtubeId: "rjtUQAz2KsU", title: "Taal Se Taal Mila", artist: "Udit Narayan, Alka Yagnik", album: "Taal", cover: "https://i.ytimg.com/vi/rjtUQAz2KsU/hqdefault.jpg" },
      { youtubeId: "HZndlyhlBHQ", title: "Kaali Kaali Aankhen", artist: "Sonu Nigam, Alka Yagnik", album: "Chhupa Rustam", cover: "https://i.ytimg.com/vi/HZndlyhlBHQ/hqdefault.jpg" },
    ],
  },
];
