export interface Track {
  youtubeId: string;
  title: string;
  artist: string;
  album: string;
  cover: string | null;
}

export const TRACKS: Track[] = [
  { youtubeId: "N0jnLZxYwYc", title: "Mujhse Mohabbat Ka Izhaar Karta", artist: "Satrang Music Official", album: "Mujhse Mohabbat Ka Izhaar Karta - Single", cover: "/covers/N0jnLZxYwYc.jpg" },
  { youtubeId: "3NWMK2MRqIk", title: "Tumsa Koi Pyaara", artist: "Kumar Sanu & Alka Yagnik", album: "Khuddar (Original Motion Picture Soundtrack)", cover: "/covers/3NWMK2MRqIk.jpg" },
  { youtubeId: "bga_0ziOOfQ", title: "Woh Meri Neend Mera Chain", artist: "Sadhana Sargam", album: "Hum Hain Rahi Pyar Ke (Original Motion Picture Soundtrack)", cover: "/covers/bga_0ziOOfQ.jpg" },
  { youtubeId: "oFxbBeYhLqM", title: "Saaton Janam Main Tere", artist: "Kumar Sanu & Alka Yagnik", album: "Dilwale (Original Motion Picture Soundtrack)", cover: "/covers/oFxbBeYhLqM.jpg" },
  { youtubeId: "nNhv8A_rJTg", title: "Oye Raju Pyar Na Kariyo (Santoor Music)", artist: "Melody Vibe", album: "Oye Raju Pyar Na Kariyo (Santoor Music) - Single", cover: "/covers/nNhv8A_rJTg.jpg" },
  { youtubeId: "d3lZvNexPL0", title: "Bahut Pyar Karte Hain W/ + English Translation", artist: "", album: "", cover: null },
  { youtubeId: "CTuvMubzXpU", title: "Jeeta Tha Jiske Liye", artist: "Kumar Sanu, Alka Yagnik & Ajay Devgan", album: "Dilwale (Original Motion Picture Soundtrack)", cover: "/covers/CTuvMubzXpU.jpg" },
  { youtubeId: "i1IsLVz6T9Q", title: "Dard Karaara", artist: "Kumar Sanu & Sadhana Sargam", album: "Dum Laga Ke Haisha (Original Motion Picture Soundtrack)", cover: "/covers/i1IsLVz6T9Q.jpg" },
  { youtubeId: "5y_TCKNzAMI", title: "Tumse Milne Ko Dil", artist: "Alka Yagnik & Kumar Sanu", album: "Phool Aur Kaante (Original Motion Picture Soundtrack)", cover: "/covers/5y_TCKNzAMI.jpg" },
  { youtubeId: "fBylcT-TWZw", title: "Ek Sanam Chahiye Aashiqui Ke Liye", artist: "Kumar Sanu", album: "Aashiqui (Original Motion Picture Soundtrack)", cover: "/covers/fBylcT-TWZw.jpg" },
  { youtubeId: "CTNgz5gb3D8", title: "Tu Pyar Hai Kisi Aur Ka (From \"Dil Hai Ke Manta Nahin\")", artist: "Anuradha Paudwal & Kumar Sanu", album: "Ultimate Romantic Duet - Kumar Sanu & Anuradha Paudwal", cover: "/covers/CTNgz5gb3D8.jpg" },
  { youtubeId: "lFdSi01tpYM", title: "Sochenge Tumhe Pyar", artist: "Kumar Sanu", album: "Deewana (Original Motion Picture Soundtrack)", cover: "/covers/lFdSi01tpYM.jpg" },
  { youtubeId: "dDR4oiyjUBA", title: "Raah Mein Unse Mulaqat", artist: "Kumar Sanu & Alka Yagnik", album: "Vijaypath (Original Motion Picture Soundtrack)", cover: "/covers/dDR4oiyjUBA.jpg" },
  { youtubeId: "otQmzlm-s7Q", title: "Main Duniya Bhula Doonga", artist: "Anuradha Paudwal & Kumar Sanu", album: "Aashiqui (Original Motion Picture Soundtrack)", cover: "/covers/otQmzlm-s7Q.jpg" },
  { youtubeId: "tPNwGuu_rQ4", title: "Tumhein Apna Banane Ki Kasam Khai Hai", artist: "Anuradha Paudwal & Kumar Sanu", album: "Sadak (Super Jhankar Beat)", cover: "/covers/tPNwGuu_rQ4.jpg" },
  { youtubeId: "p1jhKCIoVjI", title: "Tum dil ki dhakdan mein rehete ho", artist: "", album: "unplugged", cover: null },
  { youtubeId: "2OsyNo53MzU", title: "Mere Rashke Qamar (From \"Baadshaho\")", artist: "Nusrat Fateh Ali Khan, Rahat Fateh Ali Khan & Tanishk Bagchi", album: "Mere Rashke Qamar (From \"Baadshaho\") - Single", cover: "/covers/2OsyNo53MzU.jpg" },
  { youtubeId: "-N-k56i7M2k", title: "Maine Pyar Tumhi Se Kiya Hai", artist: "Anuradha Paudwal & Kumar Sanu", album: "Phool Aur Kaante (Original Motion Picture Soundtrack)", cover: "/covers/-N-k56i7M2k.jpg" },
  { youtubeId: "rXHY4Cv9cA8", title: "Ab Tere Bin Ji Lenge Hum (From \"Aashiqui: Super Jhankar Beat\")", artist: "Kumar Sanu", album: "Super Jhankar Beats - Soulful Hits", cover: "/covers/rXHY4Cv9cA8.jpg" },
  { youtubeId: "qGOTe3KmCdY", title: "Kitna Haseen Chehra", artist: "Kumar Sanu", album: "Dilwale (Original Motion Picture Soundtrack)", cover: "/covers/qGOTe3KmCdY.jpg" },
  { youtubeId: "cGKBs7rokos", title: "Tujhko Na Dekhu Toh", artist: "Udit Narayan", album: "Tujhko Na Dekhu Toh - Single", cover: "/covers/cGKBs7rokos.jpg" },
  { youtubeId: "BtdiNnrftYM", title: "Tum Se Achcha Kaun Hai Chand Tare Phool", artist: "Tauseef Akhtar", album: "Tum Se Achcha Kaun Hain (Original Motion Picture Soundtrack)", cover: "/covers/BtdiNnrftYM.jpg" },
  { youtubeId: "nRJ8vHpi6_g", title: "Tum Dil Ki Dhadkan Mein. (From \"Dhadkan\")", artist: "Abhijeet & Alka Yagnik", album: "Bollywood Actors Birthdays in August (Arbaaz Khan, Suniel Shetty and Saif Ali Khan)", cover: "/covers/nRJ8vHpi6_g.jpg" },
  { youtubeId: "xKx_80QM2LU", title: "Sab Kuchh Bhula Diya", artist: "Sonu Nigam & Sapna Awasthi", album: "Hum Tumhare Hain Sanam (Original Motion Picture Soundtrack)", cover: "/covers/xKx_80QM2LU.jpg" },
  { youtubeId: "zuPoUsdXrqM", title: "Dheere Dheere Pyar Ko Badhana Hai", artist: "Nitesh kachhap", album: "Dheere Dheere Pyar Ko Badhana Hai - Single", cover: "/covers/zuPoUsdXrqM.jpg" },
  { youtubeId: "wYdXuNtJkPk", title: "Jeeye to Jeeye Kaise", artist: "Pankaj Udhas", album: "Saajan (Original Motion Picture Soundtrack)", cover: "/covers/wYdXuNtJkPk.jpg" },
  { youtubeId: "wuLJtA0uJro", title: "Hum Lakh Chupaye Pyar Magar", artist: "Vik4s M", album: "Hum Lakh Chupaye Pyar Magar - Single", cover: "/covers/wuLJtA0uJro.jpg" },
  { youtubeId: "RjJxWRFfG3s", title: "Nahin Yeh Ho Nahin Sakta", artist: "Kumar Sanu & Sadhana Sargam", album: "Barsaat (Original Motion Picture Soundtrack)", cover: "/covers/RjJxWRFfG3s.jpg" },
  { youtubeId: "2nypvYilIkA", title: "Kahin Mujhe Pyar Hua Toh Nahin", artist: "Alka Yagnik & Kumar Sanu", album: "Rang (Original Motion Picture Soundtrack)", cover: "/covers/2nypvYilIkA.jpg" },
  { youtubeId: "_p0QrO4Mq9Q", title: "Tera Naam Liya Tujhe Yaad Kiya", artist: "Alka Yagnik", album: "Tera Naam Liya Tujhe Yaad Kiya - Single", cover: "/covers/_p0QrO4Mq9Q.jpg" },
  { youtubeId: "wV8njoRVefQ", title: "Kitna Pyaara Tujhe Rabne Banaya", artist: "Alka Yagnik & Udit Narayan", album: "Raja Hindustani (Original Motion Picture Soundtrack)", cover: "/covers/wV8njoRVefQ.jpg" },
  { youtubeId: "4ImdbyqnH8w", title: "Hum Pyaar Hai Tumhare", artist: "Kumar Sanu & Alka Yagnik", album: "Haan Maine Bhi Pyaar Kiya (Original Motion Picture Soundtrack)", cover: "/covers/4ImdbyqnH8w.jpg" },
  { youtubeId: "htMvfOfixuM", title: "Ek Ladki Ko Dekha", artist: "Kumar Sanu", album: "1942 A Love Story (Original Motion Picture Soundtrack)", cover: "/covers/htMvfOfixuM.jpg" },
  { youtubeId: "5dWbn_qER3s", title: "Tere Dar Par Sanam (Male Version)", artist: "Kumar Sanu", album: "Phir Teri Kahani Yaad Aayee (Original Motion Picture Soundtrack)", cover: "/covers/5dWbn_qER3s.jpg" },
  { youtubeId: "6Na7GSV9bVY", title: "Chura Ke Dil Mera (From \"Main Khiladi Tu Anari\")", artist: "Kumar Sanu & Alka Yagnik", album: "Sensuous Hits of Shilpa Shetty", cover: "/covers/6Na7GSV9bVY.jpg" },
  { youtubeId: "oEg_iXEWlt4", title: "Tu Meri Zindagi Hai", artist: "Anuradha Paudwal & Kumar Sanu", album: "Aashiqui (Original Motion Picture Soundtrack)", cover: "/covers/oEg_iXEWlt4.jpg" },
  { youtubeId: "QjqKXFGM3eI", title: "Chori Chori Dil Tera Churayenge (LoFI)", artist: "Lata Mangeshkar", album: "Purani Yaden Sadabahar LoFi (Original Motion Picture Soundtrack)", cover: "/covers/QjqKXFGM3eI.jpg" },
  { youtubeId: "Dz1Ad3cdtQA", title: "Ek Aisi Ladki Thi Jise Mai Pyar Karta Tha... Kumar Sanu and Alka Yagnik ... Nadeem Shravan.flv", artist: "", album: "", cover: null },
  { youtubeId: "G7AdjVDBLO8", title: "Achha Sila Diya Toone Mere Pyar Ka", artist: "", album: "Bewafa Sanam", cover: null },
  { youtubeId: "TgHYW8ubFko", title: "Tere Dard Se Dil", artist: "Kumar Sanu", album: "Deewana (Original Motion Picture Soundtrack)", cover: "/covers/TgHYW8ubFko.jpg" },
  { youtubeId: "yWAWNe74vgM", title: "Na Kajare Ki Dhar mohra Full 1080p bollyhd nettube myodi", artist: "", album: "", cover: null },
  { youtubeId: "uIOrAkrjwp4", title: "Hum Yaar Hai Tumhare", artist: "Udit Narayan & Alka Yagnik", album: "Haan Maine Bhi Pyaar Kiya (Original Motion Picture Soundtrack)", cover: "/covers/uIOrAkrjwp4.jpg" },
  { youtubeId: "HoMSu1iw0Zw", title: "Aitbaar Nahi Karna", artist: "Abhijeet & Sadhana Sargam", album: "Qayamat (Original Motion Picture Soundtrack)", cover: "/covers/HoMSu1iw0Zw.jpg" },
  { youtubeId: "WAgJ8KM5AVQ", title: "Dekha Hai Pehli Baar", artist: "Alka Yagnik & S.P. Balasubrahmanyam", album: "Saajan (Original Motion Picture Soundtrack)", cover: "/covers/WAgJ8KM5AVQ.jpg" },
  { youtubeId: "OgocnLh9P1M", title: "Aankh Hai Bhari Bhari (Duet Version) [From \"Tum Se Achcha Kaun Hai\"]", artist: "Kumar Sanu & Alka Yagnik", album: "Aankh Hai Bhari Bhari (Duet Version) [From \"Tum Se Achcha Kaun Hai\"] - Single", cover: "/covers/OgocnLh9P1M.jpg" },
  { youtubeId: "Zi9UBJQMz3I", title: "Kya Karte They Sajna Phir Lehraya Lal Dupatta", artist: "", album: "", cover: null },
  { youtubeId: "_dUAVM5ERXA", title: "Dekhne Waalon Ne (Remix)", artist: "Alka Yagnik & Udit Narayan", album: "Dekhne Waalon Ne - Single", cover: "/covers/_dUAVM5ERXA.jpg" },
  { youtubeId: "lRBIcaSV-Ns", title: "Tum To Thehre Pardesi", artist: "Altaf Raja", album: "Tum To Thehre Pardesi", cover: "/covers/lRBIcaSV-Ns.jpg" },
  { youtubeId: "9v2bq2JHt4I", title: "Chehra Kya Dekhte Ho", artist: "Asha Bhosle & Kumar Sanu", album: "Salaami (Original Motion Picture Soundtrack)", cover: "/covers/9v2bq2JHt4I.jpg" },
  { youtubeId: "Gg9ZUppafLo", title: "Too Shayar Hai Main Teri Shayari", artist: "", album: "", cover: null },
  { youtubeId: "w89fWEelFns", title: "Paas Woh Aane Lage", artist: "Kumar Sanu & Alka Yagnik", album: "Main Khiladi Tu Anari (Original Motion Picture Soundtrack)", cover: "/covers/w89fWEelFns.jpg" },
  { youtubeId: "fg9G1dacXjk", title: "Chhupana Bhi Nahin Aata", artist: "", album: "Baazigar", cover: null },
  { youtubeId: "Y-o8NQ8Y36A", title: "Is Tarah Aashiqui Ka (Kumar Sanu Version)", artist: "Kumar Sanu", album: "Imtihan (Original Motion Picture Soundtrack)", cover: "/covers/Y-o8NQ8Y36A.jpg" },
  { youtubeId: "526hvVlBP1U", title: "Tumse Milna Video", artist: "", album: "Tere Naam", cover: null },
  { youtubeId: "iCZfjggJg3M", title: "Kyo Kisi Ko", artist: "", album: "Tere Naam", cover: null },
  { youtubeId: "BaAoZA0fup0", title: "Dil Ka Aalam", artist: "", album: "Aashiqui", cover: null },
  { youtubeId: "cBGDDBHN22U", title: "Pehli Pehli Baar Mohabbat Ki Hai", artist: "", album: "Sirf Tum", cover: null },
  { youtubeId: "nG85YFR3o6U", title: "Tune Dil Mera Toda Kahi", artist: "", album: "Sanam Bewafa", cover: null },
  { youtubeId: "TRUuSFW80Rk", title: "Kaash Kahin Aisa Hota", artist: "", album: "Akshay Kumar & Raveena Tandon", cover: null },
  { youtubeId: "-pIMyf5dOnA", title: "Aawara Hawa Ka Jhonka Hoon", artist: "", album: "", cover: null },
  { youtubeId: "GxaTSDnI71w", title: "Love Tujhe Love Main Karta Hoon", artist: "", album: "Teri Adaaon Pe Marta Hoon ❤️", cover: null },
  { youtubeId: "XWKazQwFFdY", title: "Tere Dard Se Dil Aabad Raha", artist: "", album: "Deewana Movie", cover: null },
  { youtubeId: "9f6GhUb-WdM", title: "Dil Cheer Ke Dekh", artist: "", album: "Divya Bharti", cover: null },
  { youtubeId: "rMbQufI9xQw", title: "Premi Aashiq Aawaara", artist: "", album: "Kumar Sanu", cover: null },
  { youtubeId: "Mfeg92XPXik", title: "Dil Diwana", artist: "", album: "", cover: null },
];
